# Generated by Django 2.1 on 2018-09-03 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarks', models.CharField(max_length=2500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 9, 3, 13, 49, 19, 838605, tzinfo=utc))),
                # ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faces_in_shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 9, 3, 13, 49, 19, 865818, tzinfo=utc))),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Faces')),
            ],
        ),
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.IntegerField()),
                ('local_id', models.IntegerField()),
                ('shop_uuid', models.UUIDField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 9, 3, 13, 49, 19, 866471, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_uuid', models.UUIDField(default=uuid.UUID('a784a45f-7071-47fa-ba02-487b45a85b13'), unique=True)),
                ('shop_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='locals',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Shops', to_field='shop_uuid'),
        ),
        migrations.AddField(
            model_name='faces_in_shops',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Locals'),
        ),
        migrations.AddField(
            model_name='faces_in_shops',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Shops', to_field='shop_uuid'),
        ),
    ]
