# Generated by Django 2.1 on 2018-09-05 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20180904_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.AlterField(
            model_name='faces',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 9, 46, 4, 287096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faces_in_shops',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 9, 46, 4, 288525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='locals',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_uuid',
            field=models.UUIDField(default=uuid.UUID('65e28750-7326-4112-9c39-e50282706a3c'), unique=True),
        ),
    ]
