# Generated by Django 2.1 on 2018-09-05 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20180905_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faces',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 9, 55, 5, 521878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faces_in_shops',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 9, 55, 5, 523634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_uuid',
            field=models.UUIDField(default=uuid.UUID('469274a0-daf4-4965-bc83-fec572f3a772'), unique=True),
        ),
    ]
